name: Generate Documentation and Update gh-pages

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
  workflow_dispatch:

jobs:
  doc:
    name: doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Checkout gh-pages and fast-forward
        run: |
          git fetch origin main
          git merge origin/main
          git push origin gh-pages

      - name: Generate documentation
        run: bun run doc

      - name: Commit documentation changes
        run: |
          git config --local user.email "kevyn.fyleyssant+js-utils@gmail.com"
          git config --local user.name "Github Workflow"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Generate documentation"

      - name: Push changes to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
